[build]
  command = "npm run build"
   functions = "netlify/functions"
  publish = "dist"

[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_PATH = "/usr/bin/google-chrome-stable"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]