[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUPPETEER_EXECUTABLE_PATH = "/opt/build/repo/node_modules/puppeteer/.local-chromium/linux-1120561549/chrome-linux/chrome"

